//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACHEQA_Parametric_Automation_Admin.DominoAuthenticationClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DominoAuthenticationClient.IDominoLogin")]
    public interface IDominoLogin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDominoLogin/ValidateDominoUser", ReplyAction="http://tempuri.org/IDominoLogin/ValidateDominoUserResponse")]
        bool ValidateDominoUser(string Server, string Username, string Password, ref string err, int AppID, string IPAddress);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDominoLoginChannel : ACHEQA_Parametric_Automation_Admin.DominoAuthenticationClient.IDominoLogin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DominoLoginClient : System.ServiceModel.ClientBase<ACHEQA_Parametric_Automation_Admin.DominoAuthenticationClient.IDominoLogin>, ACHEQA_Parametric_Automation_Admin.DominoAuthenticationClient.IDominoLogin {
        
        public DominoLoginClient() {
        }
        
        public DominoLoginClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DominoLoginClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DominoLoginClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DominoLoginClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ValidateDominoUser(string Server, string Username, string Password, ref string err, int AppID, string IPAddress) {
            return base.Channel.ValidateDominoUser(Server, Username, Password, ref err, AppID, IPAddress);
        }
    }
}
